pages:
  image: python:3.9
  artifacts:
    paths:
      - public

  before_script:
    - mkdir public
    - pip install nbconvert pandas seaborn matplotlib ipython ipykernel

  script:
    - jupyter nbconvert --execute --to html fuel-prices-notebook.ipynb
    - mv fuel-prices-notebook.html public/index.html